### ISSUE TITLE
Add smart light bulbs support

### ISSUE THREAD

**Issue by guyluz11** [guyluz11/infinite_horizons#193]
Let's add support for the app to set the smart light bulb brightness based on the time of day, and color based on the type of activity the user is doing.

**Comment by guyluz11** [comment]
Some packages for controlling smart light bulbs from different companies

```
  dart_ewelink_api:
    git:
      url: "https://github.com/guyluz11/dart_ewelink_api.git"
      ref: "develop"
```

```
  hue_dart:
    git:
      url: "https://github.com/guyluz11/hue_dart.git"
```

```
  # Implementation of the LIFX HTTP API
  lifx_http_api: ^0.0.17
```

```
  mi_iot_token: ^1.1.0
```

```
  # Communicate with Shelly smart devices
  shelly:
    git: "https://github.com/CyBear-Jinni/shelly.git"
```

```
  # Dart library for controlling Yeelight products over LAN.
  yeedart: ^0.3.2
```
