### ISSUE TITLE
Add support for smart TV

### ISSUE THREAD

**Issue by guyluz11** [guyluz11/infinite_horizons#195]
After incorporating music support #194 we should add support to play the music through smart TV.

**Comment by guyluz11** [comment]
Package to control smart TV

  ```
cast: 
    git: 
      url: "https://github.com/guyluz11/flutter_cast.git"
      ref: "multicast_version"
```


https://pub.dev/packages/tizen_api
